
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 24 2019 21:52:10 IST (Nov 24 2019 16:22:10 UTC)

// Verification Directory fv/hamming_precompute 

module hamming_precompute(m, y);
  input [15:0] m;
  output [20:0] y;
  wire [15:0] m;
  wire [20:0] y;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_35, n_36, n_37, n_38, n_39, n_40;
  assign y[2] = m[0];
  assign y[4] = m[1];
  assign y[5] = m[2];
  assign y[6] = m[3];
  assign y[8] = m[4];
  assign y[9] = m[5];
  assign y[10] = m[6];
  assign y[11] = m[7];
  assign y[12] = m[8];
  assign y[13] = m[9];
  assign y[14] = m[10];
  assign y[16] = m[11];
  assign y[17] = m[12];
  assign y[18] = m[13];
  assign y[19] = m[14];
  assign y[20] = m[15];
  OAI21XL g357(.A0 (n_38), .A1 (n_39), .B0 (n_40), .Y (y[3]));
  OAI21XL g358(.A0 (n_35), .A1 (n_36), .B0 (n_37), .Y (y[0]));
  NAND2XL g359(.A (n_39), .B (n_38), .Y (n_40));
  NAND2XL g360(.A (n_36), .B (n_35), .Y (n_37));
  AOI21XL g364(.A0 (n_31), .A1 (n_30), .B0 (n_32), .Y (n_38));
  OAI21XL g363(.A0 (n_28), .A1 (m[11]), .B0 (n_29), .Y (n_35));
  OAI21XL g362(.A0 (n_22), .A1 (n_23), .B0 (n_24), .Y (y[7]));
  OAI21XL g361(.A0 (n_25), .A1 (n_26), .B0 (n_27), .Y (y[1]));
  NOR2XL g366(.A (n_31), .B (n_30), .Y (n_32));
  NAND2XL g365(.A (m[11]), .B (n_28), .Y (n_29));
  NAND2XL g367(.A (n_26), .B (n_25), .Y (n_27));
  NAND2XL g368(.A (n_23), .B (n_22), .Y (n_24));
  INVXL g371(.A (n_28), .Y (n_30));
  OAI21XL g370(.A0 (n_21), .A1 (m[12]), .B0 (n_19), .Y (n_25));
  AOI21XL g372(.A0 (m[7]), .A1 (n_21), .B0 (n_18), .Y (n_22));
  OAI21XL g369(.A0 (n_12), .A1 (n_13), .B0 (n_14), .Y (y[15]));
  AOI21XL g373(.A0 (n_16), .A1 (n_15), .B0 (n_17), .Y (n_28));
  NAND2XL g374(.A (m[12]), .B (n_21), .Y (n_19));
  NOR2XL g375(.A (m[7]), .B (n_21), .Y (n_18));
  NOR2XL g376(.A (n_16), .B (n_15), .Y (n_17));
  NAND2XL g377(.A (n_13), .B (n_12), .Y (n_14));
  AOI21XL g378(.A0 (m[15]), .A1 (n_9), .B0 (n_10), .Y (n_12));
  AOI21XL g379(.A0 (n_7), .A1 (n_6), .B0 (n_8), .Y (n_21));
  AOI21XL g380(.A0 (n_4), .A1 (n_11), .B0 (n_5), .Y (n_26));
  AOI21XL g381(.A0 (n_2), .A1 (n_11), .B0 (n_3), .Y (n_36));
  OAI21XL g382(.A0 (n_0), .A1 (m[15]), .B0 (n_1), .Y (n_15));
  NOR2XL g384(.A (m[15]), .B (n_9), .Y (n_10));
  NOR2XL g385(.A (n_7), .B (n_6), .Y (n_8));
  NOR2XL g386(.A (n_4), .B (n_11), .Y (n_5));
  NOR2XL g387(.A (n_2), .B (n_11), .Y (n_3));
  NAND2XL g383(.A (m[15]), .B (n_0), .Y (n_1));
  CLKXOR2X1 g392(.A (m[12]), .B (m[14]), .Y (n_13));
  XNOR2X1 g399(.A (m[8]), .B (m[10]), .Y (n_0));
  XNOR2X1 g394(.A (m[4]), .B (m[6]), .Y (n_2));
  XNOR2X1 g395(.A (m[11]), .B (m[13]), .Y (n_9));
  CLKXOR2X1 g397(.A (m[4]), .B (m[8]), .Y (n_23));
  CLKXOR2X1 g393(.A (m[0]), .B (m[13]), .Y (n_11));
  XNOR2X1 g398(.A (m[1]), .B (m[3]), .Y (n_16));
  XNOR2X1 g388(.A (m[5]), .B (m[9]), .Y (n_6));
  XNOR2X1 g396(.A (m[2]), .B (m[9]), .Y (n_31));
  CLKXOR2X1 g389(.A (m[6]), .B (m[10]), .Y (n_7));
  CLKXOR2X1 g390(.A (m[7]), .B (m[14]), .Y (n_39));
  XNOR2X1 g391(.A (m[2]), .B (m[3]), .Y (n_4));
endmodule

