
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 25 2019 00:46:55 IST (Nov 24 2019 19:16:55 UTC)

// Verification Directory fv/hamming_decoder 

module hamming_decoder(ip, op, p);
  input [20:0] ip;
  output [15:0] op;
  output [4:0] p;
  wire [20:0] ip;
  wire [15:0] op;
  wire [4:0] p;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_56, n_59;
  wire n_61, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_98, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_146, n_147;
  TLATXL \op_reg[8] (.G (n_115), .D (n_100), .Q (op[8]), .QN
       (UNCONNECTED));
  TLATXL \op_reg[14] (.G (n_115), .D (n_112), .Q (op[14]), .QN
       (UNCONNECTED0));
  TLATXL \op_reg[1] (.G (n_115), .D (n_90), .Q (op[1]), .QN
       (UNCONNECTED1));
  TLATXL \op_reg[12] (.G (n_115), .D (n_105), .Q (op[12]), .QN
       (UNCONNECTED2));
  TLATXL \op_reg[0] (.G (n_115), .D (n_81), .Q (op[0]), .QN
       (UNCONNECTED3));
  TLATXL \op_reg[15] (.G (n_115), .D (n_93), .Q (op[15]), .QN
       (UNCONNECTED4));
  TLATXL \op_reg[7] (.G (n_115), .D (n_107), .Q (op[7]), .QN
       (UNCONNECTED5));
  TLATXL \op_reg[11] (.G (n_115), .D (n_86), .Q (op[11]), .QN
       (UNCONNECTED6));
  TLATXL \op_reg[4] (.G (n_115), .D (n_79), .Q (op[4]), .QN
       (UNCONNECTED7));
  TLATXL \op_reg[3] (.G (n_115), .D (n_101), .Q (op[3]), .QN
       (UNCONNECTED8));
  TLATXL \op_reg[13] (.G (n_115), .D (n_85), .Q (op[13]), .QN
       (UNCONNECTED9));
  TLATXL \op_reg[10] (.G (n_115), .D (n_88), .Q (op[10]), .QN
       (UNCONNECTED10));
  TLATXL \op_reg[6] (.G (n_115), .D (n_98), .Q (op[6]), .QN
       (UNCONNECTED11));
  TLATXL \op_reg[5] (.G (n_115), .D (n_103), .Q (op[5]), .QN
       (UNCONNECTED12));
  TLATXL \op_reg[9] (.G (n_115), .D (ip[13]), .Q (op[9]), .QN
       (UNCONNECTED13));
  TLATXL \op_reg[2] (.G (n_115), .D (n_109), .Q (op[2]), .QN
       (UNCONNECTED14));
  NAND4XL g1927(.A (n_111), .B (n_106), .C (n_102), .D (n_114), .Y
       (n_115));
  NOR4XL g1928(.A (n_78), .B (n_146), .C (n_84), .D (n_113), .Y
       (n_114));
  NAND4XL g1929(.A (n_147), .B (n_108), .C (n_104), .D (n_110), .Y
       (n_113));
  OAI21XL g1936(.A0 (n_111), .A1 (ip[19]), .B0 (n_96), .Y (n_112));
  NOR2XL g1930(.A (n_87), .B (n_95), .Y (n_110));
  OAI21XL g1932(.A0 (n_108), .A1 (ip[5]), .B0 (n_92), .Y (n_109));
  OAI21XL g1934(.A0 (n_106), .A1 (ip[11]), .B0 (n_91), .Y (n_107));
  OAI21XL g1935(.A0 (n_104), .A1 (ip[17]), .B0 (n_82), .Y (n_105));
  OAI21XL g1933(.A0 (n_102), .A1 (ip[9]), .B0 (n_83), .Y (n_103));
  MXI2XL g1949(.A (ip[6]), .B (n_0), .S0 (n_94), .Y (n_101));
  MXI2XL g1948(.A (ip[12]), .B (n_5), .S0 (n_147), .Y (n_100));
  MXI2XL g1947(.A (n_7), .B (ip[10]), .S0 (n_146), .Y (n_98));
  NAND2XL g1937(.A (ip[19]), .B (n_111), .Y (n_96));
  NAND4XL g1931(.A (n_94), .B (n_89), .C (n_80), .D (n_74), .Y (n_95));
  MXI2XL g1942(.A (ip[20]), .B (n_18), .S0 (n_69), .Y (n_93));
  NAND2XL g1941(.A (ip[5]), .B (n_108), .Y (n_92));
  NAND2XL g1939(.A (ip[11]), .B (n_106), .Y (n_91));
  MXI2XL g1944(.A (ip[4]), .B (n_1), .S0 (n_89), .Y (n_90));
  MXI2XL g1945(.A (n_3), .B (ip[14]), .S0 (n_87), .Y (n_88));
  MXI2XL g1950(.A (ip[16]), .B (n_24), .S0 (n_63), .Y (n_86));
  MXI2XL g1951(.A (n_4), .B (ip[18]), .S0 (n_84), .Y (n_85));
  NAND2XL g1938(.A (ip[9]), .B (n_102), .Y (n_83));
  NAND2XL g1940(.A (ip[17]), .B (n_104), .Y (n_82));
  MXI2XL g1943(.A (ip[2]), .B (n_22), .S0 (n_80), .Y (n_81));
  MXI2XL g1946(.A (n_6), .B (ip[8]), .S0 (n_78), .Y (n_79));
  NAND3XL g1953(.A (p[4]), .B (n_75), .C (n_76), .Y (n_111));
  NAND3XL g1954(.A (n_72), .B (n_71), .C (n_76), .Y (n_106));
  NAND3XL g1957(.A (n_73), .B (n_75), .C (n_67), .Y (n_108));
  AOI32XL g1952(.A0 (n_65), .A1 (n_73), .A2 (n_75), .B0 (n_68), .B1
       (n_61), .Y (n_74));
  NAND3XL g1956(.A (p[4]), .B (n_75), .C (n_70), .Y (n_104));
  NAND3XL g1955(.A (n_72), .B (n_71), .C (n_70), .Y (n_102));
  NAND2XL g1964(.A (n_68), .B (n_76), .Y (n_69));
  AND2X1 g1965(.A (n_71), .B (n_67), .Y (n_87));
  NAND2XL g1966(.A (n_66), .B (n_76), .Y (n_89));
  NAND2XL g1967(.A (n_66), .B (n_67), .Y (n_94));
  NOR2BXL g1958(.AN (n_65), .B (n_64), .Y (n_78));
  AND2X1 g1959(.A (n_68), .B (n_70), .Y (n_84));
  NAND2XL g1963(.A (n_68), .B (n_65), .Y (n_63));
  NAND2XL g1960(.A (n_66), .B (n_70), .Y (n_80));
  NOR2XL g1972(.A (n_61), .B (n_59), .Y (n_67));
  NOR2XL g1970(.A (p[1]), .B (n_59), .Y (n_76));
  NOR2XL g1969(.A (n_61), .B (p[2]), .Y (n_70));
  NOR2XL g1971(.A (p[1]), .B (p[2]), .Y (n_65));
  INVXL g1976(.A (p[2]), .Y (n_59));
  NOR2XL g1973(.A (p[4]), .B (n_56), .Y (n_66));
  NOR2XL g1974(.A (n_73), .B (n_56), .Y (n_68));
  NAND2XL g1977(.A (p[0]), .B (n_71), .Y (n_64));
  OAI21XL g1978(.A0 (n_51), .A1 (n_52), .B0 (n_53), .Y (p[2]));
  OR2X1 g1979(.A (n_72), .B (p[3]), .Y (n_56));
  NOR2XL g1980(.A (p[0]), .B (p[3]), .Y (n_75));
  NAND2XL g1981(.A (n_52), .B (n_51), .Y (n_53));
  NOR2BXL g1982(.AN (p[3]), .B (p[4]), .Y (n_71));
  AOI21XL g1983(.A0 (n_46), .A1 (n_45), .B0 (n_47), .Y (n_51));
  OAI21XL g1984(.A0 (n_48), .A1 (n_49), .B0 (n_50), .Y (p[3]));
  INVXL g1985(.A (p[1]), .Y (n_61));
  INVXL g1986(.A (p[0]), .Y (n_72));
  OAI21XL g1987(.A0 (n_39), .A1 (n_40), .B0 (n_41), .Y (p[1]));
  OAI21XL g1988(.A0 (n_42), .A1 (n_43), .B0 (n_44), .Y (p[0]));
  NAND2XL g1990(.A (n_49), .B (n_48), .Y (n_50));
  NOR2XL g1991(.A (n_46), .B (n_45), .Y (n_47));
  NAND2XL g1989(.A (n_43), .B (n_42), .Y (n_44));
  NAND2XL g1992(.A (n_40), .B (n_39), .Y (n_41));
  INVXL g1993(.A (p[4]), .Y (n_73));
  AOI21XL g1996(.A0 (n_36), .A1 (n_38), .B0 (n_37), .Y (n_48));
  OAI21XL g1994(.A0 (n_38), .A1 (n_34), .B0 (n_35), .Y (n_45));
  OAI21XL g1995(.A0 (n_28), .A1 (n_29), .B0 (n_30), .Y (p[4]));
  AOI21XL g1997(.A0 (n_26), .A1 (n_25), .B0 (n_27), .Y (n_39));
  OAI21XL g1998(.A0 (n_31), .A1 (n_32), .B0 (n_33), .Y (n_42));
  NOR2XL g2000(.A (n_36), .B (n_38), .Y (n_37));
  NAND2XL g2002(.A (n_34), .B (n_38), .Y (n_35));
  NAND2XL g1999(.A (n_32), .B (n_31), .Y (n_33));
  NAND2XL g2001(.A (n_29), .B (n_28), .Y (n_30));
  NOR2XL g2003(.A (n_26), .B (n_25), .Y (n_27));
  OAI21XL g2007(.A0 (n_19), .A1 (n_20), .B0 (n_21), .Y (n_38));
  OAI21XL g2005(.A0 (n_23), .A1 (ip[1]), .B0 (n_17), .Y (n_26));
  AOI21XL g2006(.A0 (n_12), .A1 (n_11), .B0 (n_13), .Y (n_43));
  AOI21XL g2009(.A0 (n_9), .A1 (n_8), .B0 (n_10), .Y (n_31));
  AOI21XL g2010(.A0 (ip[15]), .A1 (n_34), .B0 (n_16), .Y (n_28));
  AOI21XL g2004(.A0 (n_14), .A1 (n_36), .B0 (n_15), .Y (n_25));
  MXI2XL g2008(.A (ip[16]), .B (n_24), .S0 (n_23), .Y (n_29));
  MXI2XL g2011(.A (ip[2]), .B (n_22), .S0 (n_46), .Y (n_40));
  NAND2XL g2017(.A (n_20), .B (n_19), .Y (n_21));
  MXI2XL g2012(.A (ip[20]), .B (n_18), .S0 (n_2), .Y (n_32));
  NAND2XL g2013(.A (ip[1]), .B (n_23), .Y (n_17));
  NOR2XL g2014(.A (ip[15]), .B (n_34), .Y (n_16));
  NOR2XL g2015(.A (n_14), .B (n_36), .Y (n_15));
  NOR2XL g2016(.A (n_12), .B (n_11), .Y (n_13));
  NOR2XL g2018(.A (n_9), .B (n_8), .Y (n_10));
  INVXL g2025(.A (n_14), .Y (n_19));
  MXI2XL g2019(.A (n_7), .B (ip[10]), .S0 (ip[8]), .Y (n_9));
  MXI2XL g2022(.A (n_6), .B (ip[8]), .S0 (ip[7]), .Y (n_49));
  MXI2XL g2023(.A (n_5), .B (ip[12]), .S0 (ip[11]), .Y (n_20));
  MXI2XL g2024(.A (ip[18]), .B (n_4), .S0 (ip[17]), .Y (n_23));
  MXI2XL g2030(.A (n_3), .B (ip[14]), .S0 (ip[13]), .Y (n_14));
  MXI2XL g2032(.A (ip[20]), .B (n_18), .S0 (ip[19]), .Y (n_34));
  MXI2XL g2028(.A (ip[2]), .B (n_22), .S0 (ip[0]), .Y (n_2));
  MXI2XL g2026(.A (n_4), .B (ip[18]), .S0 (ip[16]), .Y (n_12));
  MXI2XL g2027(.A (ip[14]), .B (n_3), .S0 (ip[12]), .Y (n_11));
  MXI2XL g2021(.A (n_1), .B (ip[4]), .S0 (ip[3]), .Y (n_52));
  MXI2XL g2020(.A (ip[6]), .B (n_0), .S0 (ip[4]), .Y (n_8));
  MXI2XL g2031(.A (ip[6]), .B (n_0), .S0 (ip[5]), .Y (n_46));
  MXI2XL g2029(.A (ip[10]), .B (n_7), .S0 (ip[9]), .Y (n_36));
  INVXL g2038(.A (ip[8]), .Y (n_6));
  INVXL g2035(.A (ip[4]), .Y (n_1));
  INVXL g2041(.A (ip[16]), .Y (n_24));
  INVXL g2040(.A (ip[12]), .Y (n_5));
  INVXL g2036(.A (ip[2]), .Y (n_22));
  INVXL g2042(.A (ip[10]), .Y (n_7));
  INVXL g2037(.A (ip[20]), .Y (n_18));
  INVXL g2034(.A (ip[14]), .Y (n_3));
  INVXL g2033(.A (ip[6]), .Y (n_0));
  INVXL g2039(.A (ip[18]), .Y (n_4));
  NOR2BX1 g2(.AN (n_70), .B (n_64), .Y (n_146));
  NAND2BX1 g2059(.AN (n_64), .B (n_76), .Y (n_147));
endmodule

