
// Generated by Cadence Genus(TM) Synthesis Solution 16.21-s018_1
// Generated on: Nov 24 2019 22:46:19 IST (Nov 24 2019 17:16:19 UTC)

// Verification Directory fv/hamming_clock 

module add_unsigned(A, B, Z);
  input [4:0] A;
  input B;
  output [4:0] Z;
  wire [4:0] A;
  wire B;
  wire [4:0] Z;
  wire n_1, n_3, n_4, n_6, n_7, n_9;
  OAI21XL g32(.A0 (A[4]), .A1 (n_7), .B0 (n_9), .Y (Z[4]));
  NAND2XL g33(.A (n_7), .B (A[4]), .Y (n_9));
  OAI21XL g34(.A0 (A[3]), .A1 (n_3), .B0 (n_6), .Y (Z[3]));
  NAND2BXL g35(.AN (n_3), .B (A[3]), .Y (n_7));
  NAND2XL g36(.A (n_3), .B (A[3]), .Y (n_6));
  OAI21XL g37(.A0 (A[2]), .A1 (n_1), .B0 (n_4), .Y (Z[2]));
  NAND2XL g38(.A (n_1), .B (A[2]), .Y (n_4));
  NAND2BXL g39(.AN (n_1), .B (A[2]), .Y (n_3));
  MXI2XL g40(.A (Z[0]), .B (A[0]), .S0 (A[1]), .Y (Z[1]));
  NAND2XL g41(.A (A[0]), .B (A[1]), .Y (n_1));
  CLKINVX1 g42(.A (A[0]), .Y (Z[0]));
endmodule

module hamming_clock(m, clk, e, i);
  input [15:0] m;
  input clk;
  output [20:0] e;
  output [4:0] i;
  wire [15:0] m;
  wire clk;
  wire [20:0] e;
  wire [4:0] i;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED_HIER_Z, n_0, n_1, n_2,
       n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_73;
  wire n_74, n_75, n_76, n_77, n_83, p0, p1, p2;
  wire p3, p4;
  add_unsigned add_73_4(.A ({n_49, i[3:0]}), .B (UNCONNECTED_HIER_Z),
       .Z ({n_73, n_74, n_75, n_76, n_77}));
  BUFX2 cdn_loop_breaker(.A (n_76), .Y (n_50));
  BUFX2 cdn_loop_breaker105(.A (i[4]), .Y (n_49));
  BUFX2 cdn_loop_breaker106(.A (n_83), .Y (n_48));
  BUFX2 cdn_loop_breaker107(.A (n_75), .Y (n_47));
  BUFX2 cdn_loop_breaker108(.A (n_74), .Y (n_46));
  BUFX2 cdn_loop_breaker109(.A (n_77), .Y (n_45));
  NOR2BXL g473(.AN (n_46), .B (n_48), .Y (i[3]));
  NOR2BXL g474(.AN (n_47), .B (n_48), .Y (i[2]));
  OR2X1 g475(.A (n_45), .B (n_48), .Y (i[0]));
  NOR2BXL g476(.AN (n_50), .B (n_48), .Y (i[1]));
  TLATXL \e_reg[20] (.G (n_83), .D (m[15]), .Q (e[20]), .QN
       (UNCONNECTED));
  TLATXL \e_reg[19] (.G (n_83), .D (m[14]), .Q (e[19]), .QN
       (UNCONNECTED0));
  TLATXL \e_reg[17] (.G (n_83), .D (m[12]), .Q (e[17]), .QN
       (UNCONNECTED1));
  TLATXL \e_reg[13] (.G (n_83), .D (m[9]), .Q (e[13]), .QN
       (UNCONNECTED2));
  TLATXL \e_reg[5] (.G (n_83), .D (m[2]), .Q (e[5]), .QN
       (UNCONNECTED3));
  TLATXL \e_reg[4] (.G (n_83), .D (m[1]), .Q (e[4]), .QN
       (UNCONNECTED4));
  TLATXL \e_reg[12] (.G (n_83), .D (m[8]), .Q (e[12]), .QN
       (UNCONNECTED5));
  TLATXL \e_reg[3] (.G (n_83), .D (p2), .Q (e[3]), .QN (UNCONNECTED6));
  TLATXL \e_reg[2] (.G (n_83), .D (m[0]), .Q (e[2]), .QN
       (UNCONNECTED7));
  TLATXL \e_reg[16] (.G (n_83), .D (m[11]), .Q (e[16]), .QN
       (UNCONNECTED8));
  TLATXL \e_reg[15] (.G (n_83), .D (p4), .Q (e[15]), .QN
       (UNCONNECTED9));
  TLATXL \e_reg[1] (.G (n_83), .D (p1), .Q (e[1]), .QN (UNCONNECTED10));
  TLATXL \e_reg[0] (.G (n_83), .D (p0), .Q (e[0]), .QN (UNCONNECTED11));
  TLATXL \e_reg[10] (.G (n_83), .D (m[6]), .Q (e[10]), .QN
       (UNCONNECTED12));
  TLATXL \e_reg[18] (.G (n_83), .D (m[13]), .Q (e[18]), .QN
       (UNCONNECTED13));
  TLATXL \e_reg[11] (.G (n_83), .D (m[7]), .Q (e[11]), .QN
       (UNCONNECTED14));
  TLATXL \e_reg[9] (.G (n_83), .D (m[5]), .Q (e[9]), .QN
       (UNCONNECTED15));
  TLATXL \e_reg[8] (.G (n_83), .D (m[4]), .Q (e[8]), .QN
       (UNCONNECTED16));
  TLATXL \e_reg[14] (.G (n_83), .D (m[10]), .Q (e[14]), .QN
       (UNCONNECTED17));
  TLATXL \e_reg[7] (.G (n_83), .D (p3), .Q (e[7]), .QN (UNCONNECTED18));
  TLATXL \e_reg[6] (.G (n_83), .D (m[3]), .Q (e[6]), .QN
       (UNCONNECTED19));
  NOR3BXL g520(.AN (i[4]), .B (i[0]), .C (n_51), .Y (n_83));
  NAND3BXL g521(.AN (i[3]), .B (i[2]), .C (i[1]), .Y (n_51));
  NOR2BXL g522(.AN (n_73), .B (n_48), .Y (i[4]));
  TLATX1 p0_reg(.G (i[0]), .D (n_43), .Q (p0), .QN (UNCONNECTED20));
  TLATNX1 p1_reg(.GN (n_28), .D (n_44), .Q (p1), .QN (UNCONNECTED21));
  TLATNX1 p2_reg(.GN (n_27), .D (n_42), .Q (p2), .QN (UNCONNECTED22));
  TLATX1 p3_reg(.G (i[3]), .D (n_41), .Q (p3), .QN (UNCONNECTED23));
  TLATX1 p4_reg(.G (n_8), .D (n_40), .Q (p4), .QN (UNCONNECTED24));
  MXI2XL g1549(.A (n_38), .B (n_39), .S0 (p1), .Y (n_44));
  MXI2XL g1550(.A (n_38), .B (n_39), .S0 (p0), .Y (n_43));
  MXI2XL g1551(.A (n_38), .B (n_39), .S0 (p2), .Y (n_42));
  MXI2XL g1552(.A (n_38), .B (n_39), .S0 (p3), .Y (n_41));
  MXI2XL g1553(.A (n_38), .B (n_39), .S0 (p4), .Y (n_40));
  NAND2XL g1554(.A (n_32), .B (n_37), .Y (n_39));
  NAND2BXL g1555(.AN (n_37), .B (n_32), .Y (n_38));
  AOI221XL g1556(.A0 (i[4]), .A1 (n_25), .B0 (n_24), .B1 (m[11]), .C0
       (n_36), .Y (n_37));
  OAI211XL g1557(.A0 (n_21), .A1 (n_18), .B0 (n_30), .C0 (n_35), .Y
       (n_36));
  AOI31XL g1558(.A0 (m[2]), .A1 (n_9), .A2 (n_4), .B0 (n_34), .Y
       (n_35));
  OAI211XL g1559(.A0 (n_20), .A1 (n_17), .B0 (n_31), .C0 (n_33), .Y
       (n_34));
  NAND3BXL g1560(.AN (n_26), .B (i[1]), .C (i[2]), .Y (n_33));
  AOI32XL g1561(.A0 (m[8]), .A1 (n_1), .A2 (n_19), .B0 (n_29), .B1
       (n_7), .Y (n_31));
  AOI222XL g1562(.A0 (n_22), .A1 (n_10), .B0 (n_23), .B1 (n_9), .C0
       (n_5), .C1 (n_24), .Y (n_32));
  NAND3XL g1563(.A (n_13), .B (n_7), .C (m[0]), .Y (n_30));
  AO22X1 g1564(.A0 (n_14), .A1 (m[1]), .B0 (n_4), .B1 (m[3]), .Y
       (n_29));
  AOI22XL g1565(.A0 (1'b1), .A1 (1'b0), .B0 (i[1]), .B1 (n_3), .Y
       (n_28));
  AOI22XL g1566(.A0 (1'b1), .A1 (1'b0), .B0 (i[2]), .B1 (n_3), .Y
       (n_27));
  AOI22XL g1567(.A0 (m[9]), .A1 (n_16), .B0 (m[10]), .B1 (n_19), .Y
       (n_26));
  AO22X1 g1568(.A0 (n_13), .A1 (n_11), .B0 (n_14), .B1 (n_12), .Y
       (n_25));
  OR2X1 g1569(.A (n_13), .B (n_14), .Y (n_23));
  NOR2XL g1570(.A (n_15), .B (i[3]), .Y (n_24));
  OAI2BB1XL g1571(.A0N (n_7), .A1N (n_2), .B0 (n_17), .Y (n_22));
  AOI22XL g1572(.A0 (m[4]), .A1 (n_10), .B0 (m[6]), .B1 (n_0), .Y
       (n_21));
  AOI22XL g1573(.A0 (m[5]), .A1 (n_0), .B0 (m[7]), .B1 (n_1), .Y
       (n_20));
  CLKINVX1 g1574(.A (n_18), .Y (n_19));
  CLKINVX1 g1575(.A (n_17), .Y (n_16));
  NAND2XL g1576(.A (n_10), .B (i[4]), .Y (n_15));
  NAND2XL g1577(.A (n_7), .B (i[3]), .Y (n_18));
  NAND2XL g1578(.A (n_9), .B (i[3]), .Y (n_17));
  MX2X1 g1579(.A (m[14]), .B (m[15]), .S0 (i[0]), .Y (n_12));
  MX2X1 g1580(.A (m[12]), .B (m[13]), .S0 (i[0]), .Y (n_11));
  NOR2BXL g1581(.AN (n_1), .B (i[3]), .Y (n_14));
  NOR2BXL g1582(.AN (n_0), .B (i[3]), .Y (n_13));
  NOR2XL g1583(.A (n_83), .B (n_6), .Y (n_8));
  NOR2XL g1584(.A (i[2]), .B (i[1]), .Y (n_10));
  NOR2XL g1585(.A (i[4]), .B (i[0]), .Y (n_9));
  NOR2XL g1588(.A (i[4]), .B (n_5), .Y (n_7));
  CLKINVX1 g1590(.A (i[4]), .Y (n_6));
  CLKINVX1 g1591(.A (i[0]), .Y (n_5));
  CLKINVX1 g1592(.A (n_51), .Y (n_4));
  CLKINVX1 g1593(.A (n_83), .Y (n_3));
  CLKINVX1 g1595(.A (i[3]), .Y (n_2));
  NOR2BX1 g2(.AN (i[2]), .B (i[1]), .Y (n_1));
  NOR2BX1 g1596(.AN (i[1]), .B (i[2]), .Y (n_0));
endmodule

